### ISSUE TITLE
Just doesn't work out of the box

### ISSUE THREAD

**Issue by victordidenko** [bricksoft/pika-plugin-add-properties#1]
You didn't publish _built version_ to npm
```
$ pika build
@pika/pack v0.5.0
.../node_modules/pika-plugin-add-properties/src/index.js:1
export function beforeBuild({ options }) {
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (.../node_modules/import-from/index.js:4:47)
    at cleanRawDistObject (.../node_modules/@pika/pack/dist-node/index.js:3724:36)
    at Array.map (<anonymous>)
Error: Command failed with exit code 1 (EPERM): npx pika-pack
    at makeError (.../node_modules/execa/lib/error.js:59:11)
    at handlePromise (.../node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
```

**Comment by peanutbother** [comment]
Seems like there was an error in my workflow.
Thank you for creating an issue!
I will fix it asap

**Comment by peanutbother** [comment]
fixed by hotfix in release v1.0.2

**Comment by victordidenko** [comment]
Thank you! But I also were in need to _remove_ properties, so I created new plugin [pika-plugin-package.json](https://github.com/yumauri/pika-plugin-package.json), which, essentially, supersede `pika-plugin-merge-properties` and `pika-plugin-add-properties`, and also adds ability to remove properties / array items. Thank you for your plugins, I was looking in the source to get my head around pika plugin system.

**Comment by peanutbother** [comment]
Awesome!
Glad you could use it for better.
Make sure to push a pr to the pika docs to include your community plugin, so others can benefit too.

**Comment by yumauri** [comment]
Sure! https://github.com/pikapkg/builders/pull/101 :)
